services:
  services:
  db:
    image: mysql:8.0
    container_name: ecommerce-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sudeep2003
      MYSQL_DATABASE: ecommerce_db
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-psudeep2003"]
      interval: 5s
      timeout: 5s
      retries: 30

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sudeep2003
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"

volumes:
  db_data:

